FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install uv && uv pip install --no-cache-dir --system -r requirements.txt

COPY ./worker.py .
COPY ./ai_analyzer.py .
COPY ./config ./config

RUN chmod +x worker.py

ENTRYPOINT ["python", "worker.py"]
